<?php

/**
 * Implements hook_menu().
 */
function allstars_taxonomy_grid_menu() {
  $items['admin/config/allstars/taxonomy_grid'] = array(
    'title' => 'Allstars taxonomy grid settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('allstars_taxonomy_grid_admin_settings'),
    'file' => 'allstars_taxonomy_grid.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function allstars_taxonomy_grid_block_info() {
  $blocks['taxonomy_grid'] = array(
    'info' => t('Allstars taxonomy grid'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function allstars_taxonomy_grid_block_view($delta = '') {
  $block = array();
  if ($delta == 'taxonomy_grid') {
    
  }
  return $block;
}
